### ISSUE TITLE
Breaking change in v1.2.2 "WithIdentity" moved to other namespace.

### ISSUE THREAD

**Issue by manu-vilachan** [hbiarge/Acheve.Owin.Testing.Security#1]
Hi Hugo,

I don't know if you notice that with v1.2.2 you've introduce a breaking change respect v1.2.1.
The method WithIdentity has been moved to namespace Microsoft.Owin.Testing, causing changing usings statements everywhere this method is used.

Maybe a major version upgrade would be better than just the fix number.

Kind regards.

**Comment by hbiarge** [comment]
Hi manu-vilachan,
Yes, I know. That was an unfortunate decission in an unfortunate momment. Sorry for the inconveniencies.
You are rigth about the major version increment had been better, but it's too late for that.
I'll try to do versioning better in future updates.
